In [12]:
import numpy as np
import pandas as pd
import sklearn
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import pickle

check = 0
data = pd.read_csv('data.csv')
data = data[['G1','G2','G3','studytime','failures']]
    
X = np.array(data.drop(['G3'], 1) )
Y = np.array(data['G3'])
x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.1)    
  
#training    
#for _ in range(10):
#    x_train, x_test, y_train, y_test = train_test_split(X, Y, test_size = 0.1)
#    linear = LinearRegression()
#    linear.fit(x_train, y_train)
#    
#    accuracy = linear.score(x_test,y_test)
#    print(accuracy)
#    if check < accuracy:
#        check = accuracy
#        with open('grade.pickle', 'wb') as fh:
#            pickle.dump(linear, fh)

            
load = open('grade.pickle', 'rb')
linear = pickle.load(load)
predict = linear.predict(x_test)
for i in range(len(predict)):
    print(x_test[i],'         ', predict[i], '        ' ,y_test[i])

[7 5 3 1]           3.7618815953089006          0
[8 9 2 0]           8.341176522410619          10
[14 15  1  0]           15.379289027309149          16
[14 16  3  0]           15.90113867878453          16
[13 14  1  0]           14.243964664584729          13
[11 11  2  0]           10.772967302004524          11
[7 0 3 0]           -0.8137726375007107          0
[7 8 2 3]           6.320080229424568          10
[11 11  4  0]           10.320634644900538          10
[6 0 1 0]           -0.5225820345417856          0
[14 12  2  0]           12.230575773019066          11
[15 14  3  0]           14.113916115770863          15
[16 15  2  0]           15.475406807047278          15
[8 7 2 0]           6.392811905251889          6
[9 9 1 0]           8.72848490510767          10
[10  9  2  0]           8.663460630700737          11
[10 11  2  0]           10.611825247859464          12
[12 12  1  0]           12.13445799328094          13
[14 13  2  0]           13.204758081598431      